# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Run the start script
        run: ./start.sh
      - name: Run the stop script
        run: ./stop.sh
