# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Show Vagrant version
        run: vagrant --version
      - name: Make SSH key
        run: ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y >/dev/null 2>&1
      - name: Run the start script
        run: ./start.sh
      - name: Run the stop script
        run: ./stop.sh
